ci(chat): Test linting within pipeline
Add back linting with flake8 to chatserviceCi.yml to see if it will run the job correctly.

diff --git a/.github/workflows/chatserviceCI.yml b/.github/workflows/chatserviceCI.yml
--- a/.github/workflows/chatserviceCI.yml
+++ b/.github/workflows/chatserviceCI.yml
@@ -62,18 +62,18 @@ jobs:
       run: |
         docker run -d -p 8000:8000 --name chat-service chat-service
         
-    # - name: Lint with flake8
-    #   run: |
-    #     continue-on-error: true
-    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-    #     flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
+    - name: Lint with flake8
+      run: |
+        continue-on-error: true
+        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
+        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
         
-    # - name: Check if 'Lint with flake8' step failed
-    #   if: steps.flake8.outcome != 'success'
-    #   run: |
-    #     echo "flake8 fails"
-    #     exit 1
+    - name: Check if 'Lint with flake8' step failed
+      if: steps.flake8.outcome != 'success'
+      run: |
+        echo "flake8 fails"
+        exit 1
       
     - name: Test with pytest
       run: |
